import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case english
    case simplifiedChinese

    var id: String { rawValue }

    var locale: Locale {
        switch self {
        case .system: return .autoupdatingCurrent
        case .english: return Locale(identifier: "en")
        case .simplifiedChinese: return Locale(identifier: "zh-Hans")
        }
    }

    var resolved: AppLanguage {
        switch self {
        case .english, .simplifiedChinese:
            return self
        case .system:
            let identifier = Locale.autoupdatingCurrent.identifier.lowercased()
            return identifier.hasPrefix("zh") ? .simplifiedChinese : .english
        }
    }

    func label(language: AppLanguage) -> String {
        switch self {
        case .system: return L10n.t("language.system", language: language)
        case .english: return L10n.t("language.english", language: language)
        case .simplifiedChinese: return L10n.t("language.simplifiedChinese", language: language)
        }
    }

    static let storageKey = "ModelChanges.language"

    static func load() -> AppLanguage {
        guard let raw = UserDefaults.standard.string(forKey: storageKey),
              let language = AppLanguage(rawValue: raw) else {
            return .system
        }
        return language
    }
}

enum L10n {
    static func t(_ key: String, language: AppLanguage, _ args: CVarArg...) -> String {
        t(key, language: language, arguments: args)
    }

    static func t(_ key: String, language: AppLanguage, arguments: [CVarArg] = []) -> String {
        let resolved = language.resolved
        let format = tables[resolved]?[key] ?? tables[.english]?[key] ?? key
        guard !arguments.isEmpty else { return format }
        return String(format: format, locale: resolved.locale, arguments: arguments)
    }

    private static let tables: [AppLanguage: [String: String]] = [
        .english: [
            "language.system": "System",
            "language.english": "English",
            "language.simplifiedChinese": "Simplified Chinese",

            "toolbar.endpointHelp": "Connection info",
            "toolbar.settings": "Settings",
            "status.startServer": "Start server",
            "status.installOllama": "Install Ollama",
            "status.localRuntimeLive": "Local runtime is live",
            "status.clickToStart": "Click to start",
            "status.clickToInstall": "Click to install",
            "sync.syncing": "Syncing...",
            "sync.updated": "Updated %@",
            "sync.action": "Sync",
            "sync.refreshHelp": "Refresh the model list from ollama.com",
            "search.placeholder": "Search models...",
            "filter.all": "All",
            "sort.popular": "Popular",
            "sort.newest": "Newest",

            "modelType.chat": "Chat",
            "modelType.code": "Code",
            "modelType.vision": "Vision",
            "modelType.reasoning": "Reasoning",
            "modelType.embedding": "Embedding",
            "modelType.audio": "Audio",
            "fit.fits": "Fits your Mac",
            "fit.tight": "Tight fit",
            "fit.tooBig": "Too large",

            "history.deployed": "Deployed",
            "history.started": "Started",
            "history.stopped": "Stopped",
            "history.removed": "Removed",
            "history.cleared": "Removed all models",
            "history.wiped": "Reset host",

            "relative.justNow": "just now",
            "relative.minutesAgo": "%d min ago",
            "relative.hoursAgo": "%d hr ago",
            "relative.daysAgo": "%d d ago",

            "empty.noModelsTitle": "No models match",
            "empty.noModelsDescription": "Try a different search or filter.",

            "dock.nothingLoaded": "Nothing loaded in memory",
            "dock.installedHelp": "Installed models · %@ on disk",
            "dock.connect": "Connect",
            "dock.connectHelp": "Show the local endpoint for your app",
            "dock.memoryHelp": "%@ of %d GB used by loaded models. You can run several models at once while there's headroom.",
            "dock.loading": "loading",
            "dock.installedModels": "Installed models",
            "dock.noModelsDownloaded": "No models downloaded yet.",
            "dock.stopHelp": "Stop",
            "dock.loadHelp": "Load into memory",
            "dock.deleteHelp": "Delete from disk",
            "dock.removeTitle": "Remove %@?",
            "dock.removeButton": "Remove %@",

            "inspector.pulls": "Pulls",
            "inspector.tags": "Tags",
            "inspector.updated": "Updated",
            "inspector.deploy": "Deploy",
            "inspector.deployHint": "one click = download + load",
            "inspector.sizeHint": "Download sizes are estimated for Q4 quantization.",
            "inspector.viewOnOllama": "View on ollama.com",
            "inspector.ram": "~%@ RAM",
            "chip.running": "running",
            "chip.installed": "installed",
            "button.cancel": "Cancel",
            "button.stop": "Stop",
            "button.start": "Start",
            "button.deploy": "Deploy",
            "button.tooLarge": "Too large",
            "button.done": "Done",
            "button.install": "Install",
            "button.restart": "Restart",
            "button.send": "Send",
            "button.test": "Test",
            "button.remove": "Remove",
            "button.clear": "Clear",
            "button.clearHistory": "Clear history",
            "button.quit": "Quit",
            "inspector.tooLargeHelp": "Estimated to exceed this Mac's %d GB of RAM",
            "progress.loadingIntoMemory": "Loading into memory...",
            "progress.ready": "Ready",
            "progress.failed": "Failed: %@",

            "endpoint.title": "Connection",
            "endpoint.connection": "Status",
            "endpoint.urls": "Addresses",
            "endpoint.configuration": "Examples",
            "endpoint.readyTitle": "Ready to connect",
            "endpoint.waitingTitle": "Ollama is not running",
            "endpoint.live": "Use the addresses below to connect apps to this Mac.",
            "endpoint.offline": "Start Ollama before copying connection details.",
            "endpoint.baseURLs": "Base URLs",
            "endpoint.openAIBase": "OpenAI-compatible URL",
            "endpoint.primaryHint": "Use this with most apps, SDKs, and agent tools.",
            "endpoint.primaryBadge": "Recommended",
            "endpoint.nativeAPI": "Ollama URL",
            "endpoint.nativeHint": "Use this only for Ollama's native API.",
            "endpoint.model": "Model",
            "endpoint.currentModel": "Model",
            "endpoint.modelHint": "Choose the model used in examples and tests.",
            "endpoint.noModel": "No model ready",
            "endpoint.dropInConfig": "Drop-in config",
            "endpoint.snippetTitle": "Copy an example",
            "endpoint.apiKeyHint": "For local use, set the API key to ollama.",
            "endpoint.environment": "Terminal",
            "endpoint.pythonSDK": "Python",
            "endpoint.visionExample": "Vision",
            "endpoint.toolsExample": "Tools",
            "endpoint.embeddingExample": "Embeddings",
            "endpoint.copy": "Copy",
            "endpoint.copied": "Copied",
            "test.title": "Capability test",
            "test.deployFirst": "Start a model first.",
            "test.sendPrompt": "Send a message to %@.",
            "test.placeholder": "Type a short message...",
            "test.placeholderImage": "Ask about the image...",
            "test.placeholderTools": "Ask for weather in Singapore...",
            "test.placeholderEmbedding": "Text to turn into a vector...",
            "test.response": "Model response",
            "test.toolResult": "Tool call",
            "test.embeddingResult": "Embedding result",
            "test.defaultPrompt": "Say hello in one short sentence.",
            "test.defaultImagePrompt": "Describe this image in one paragraph.",
            "test.defaultToolsPrompt": "What is the weather in Singapore? Use the tool.",
            "test.defaultEmbeddingPrompt": "Local models make private AI workflows possible.",
            "test.modeText": "Text",
            "test.modeImage": "Image",
            "test.modeTools": "Tools",
            "test.modeEmbedding": "Embed",
            "test.capText": "Text chat",
            "test.capVision": "Image input",
            "test.capTools": "Tool calls",
            "test.capEmbedding": "Embeddings",
            "test.chooseImage": "Choose image",
            "test.changeImage": "Change",
            "test.pasteImage": "Paste",
            "test.pastedImage": "Pasted image",
            "test.noImageOnClipboard": "No image found on the clipboard.",
            "test.imageReady": "Ready for a vision model.",
            "test.imagePickHint": "Choose or paste one image.",
            "test.embeddingHint": "Embedding requests may require Ollama to run with embedding support enabled.",

            "settings.title": "Settings",
            "settings.basic": "General",
            "settings.language": "Language",
            "settings.languageSubtitle": "Change the app language.",
            "settings.ollama": "Local model service",
            "settings.runtime": "Runtime",
            "settings.runtimeSubtitle": "Ollama runs the models locally.",
            "settings.binary": "Binary",
            "settings.modelList": "Model list",
            "settings.modelListSubtitle": "Refresh or sort the online model list.",
            "settings.modelLibrary": "Browseable models",
            "settings.modelCount": "%d models",
            "settings.notSynced": "Not synced yet",
            "settings.keepAlive": "Unload models after",
            "settings.keepAliveSubtitle": "Choose how long idle models stay in memory.",
            "settings.fiveMin": "5 min",
            "settings.thirtyMin": "30 min",
            "settings.twoHours": "2 hr",
            "settings.forever": "Keep loaded",
            "settings.menuBarStartup": "Menu bar & startup",
            "settings.menuBarSubtitle": "The menu bar icon lets you start/stop models without opening this window.",
            "settings.launchAtLogin": "Open at login",
            "settings.launchAtLoginSubtitle": "Keep quick access available in the menu bar.",
            "settings.history": "History",
            "settings.historySubtitle": "Everything you've deployed, started, stopped or removed.",
            "settings.historyCount": "%d records",
            "settings.nothingYet": "Nothing yet.",
            "settings.storage": "Storage",
            "settings.downloadedModels": "Downloaded models",
            "settings.downloadedModelsSubtitle": "These can be downloaded again later.",
            "settings.cleanUp": "Clean up",
            "settings.cleanUpSubtitle": "Keep the host tidy - stop means stop, delete means gone.",
            "settings.modelsOnDisk": "Models on disk",
            "settings.removeAllModels": "Delete downloaded models",
            "settings.removeAllTitle": "Remove all %d models?",
            "settings.removeAllMessage": "Deletes downloaded models only. Ollama stays installed.",
            "settings.resetHost": "Remove Ollama and all app data",
            "settings.resetTitle": "Reset the host?",
            "settings.resetButton": "Remove Ollama and all model data",
            "settings.resetMessage": "Stops all models, deletes downloads, uninstalls Ollama, and removes ~/.ollama.",
            "settings.cleaning": "Cleaning up...",
            "settings.advanced": "Advanced",
            "settings.footer": "ModelChanges - browse open models live and deploy them locally with one click. Detected %d GB RAM on this Mac.",
            "runtime.ready": "Service is running",
            "runtime.running": "Ollama %@ is ready.",
            "runtime.installedNotRunning": "Service is stopped",
            "runtime.startHint": "Start it to use local models.",
            "runtime.notInstalled": "Ollama is not installed",
            "runtime.installHint": "Install it to run models on this Mac.",

            "menu.noModelsLoaded": "No models loaded",
            "menu.startInstalled": "Start model",
            "menu.launchAtLogin": "Launch at login",
            "menu.openApp": "Open",
            "menu.on": "on",
            "menu.off": "off",
            "menu.loadedCount": "%d loaded",
            "menu.serverNotRunning": "Server not running",
            "menu.ollamaNotInstalled": "Ollama not installed",

            "log.synced": "Synced %d models from ollama.com",
            "log.deploying": "Deploying %@...",
            "log.cancelled": "Cancelled %@",
            "log.ready": "%@ is ready",
            "log.stopping": "Stopping %@...",
            "log.stopped": "Stopped %@",
            "log.removing": "Removing %@...",
            "log.removed": "Removed %@",
            "log.removingAll": "Removing all models...",
            "log.removedAll": "Removed %d models",
            "log.resettingHost": "Resetting host...",
            "log.hostCleaned": "Host cleaned - Ollama uninstalled",
            "log.startingServer": "Starting Ollama server...",
            "log.serverUp": "Ollama server is up",
            "log.installingOllama": "Installing Ollama (this can take a minute)...",
            "log.ollamaInstalled": "Ollama installed",
            "log.installFailed": "Install failed - see error banner",
            "error.ollamaInstallFailed": "Ollama install failed: %@",
            "error.syncFailed": "Sync failed: %@",
            "error.homebrewNotFound": "Ollama could not be installed automatically.",
            "error.brewInstallFailed": "Ollama install failed: %@",
            "error.failedTag": "%@: %@",
            "log.failedTag": "Failed %@: %@"
        ],
        .simplifiedChinese: [
            "language.system": "跟随系统",
            "language.english": "English",
            "language.simplifiedChinese": "简体中文",

            "toolbar.endpointHelp": "连接信息",
            "toolbar.settings": "设置",
            "status.startServer": "启动服务",
            "status.installOllama": "安装 Ollama",
            "status.localRuntimeLive": "本地运行时已在线",
            "status.clickToStart": "点击启动",
            "status.clickToInstall": "点击安装",
            "sync.syncing": "同步中...",
            "sync.updated": "更新于 %@",
            "sync.action": "同步",
            "sync.refreshHelp": "从 ollama.com 刷新模型列表",
            "search.placeholder": "搜索模型...",
            "filter.all": "全部",
            "sort.popular": "热门",
            "sort.newest": "最新",

            "modelType.chat": "聊天",
            "modelType.code": "代码",
            "modelType.vision": "视觉",
            "modelType.reasoning": "推理",
            "modelType.embedding": "嵌入",
            "modelType.audio": "音频",
            "fit.fits": "适合这台 Mac",
            "fit.tight": "比较吃紧",
            "fit.tooBig": "过大",

            "history.deployed": "已部署",
            "history.started": "已启动",
            "history.stopped": "已停止",
            "history.removed": "已移除",
            "history.cleared": "已移除全部模型",
            "history.wiped": "已重置主机",

            "relative.justNow": "刚刚",
            "relative.minutesAgo": "%d 分钟前",
            "relative.hoursAgo": "%d 小时前",
            "relative.daysAgo": "%d 天前",

            "empty.noModelsTitle": "没有匹配的模型",
            "empty.noModelsDescription": "换个搜索词或筛选条件试试。",

            "dock.nothingLoaded": "内存中没有加载模型",
            "dock.installedHelp": "已安装模型 · 磁盘占用 %@",
            "dock.connect": "连接",
            "dock.connectHelp": "查看本地端点配置",
            "dock.memoryHelp": "已加载模型占用 %@ / %d GB。只要还有余量，就可以同时运行多个模型。",
            "dock.loading": "加载中",
            "dock.installedModels": "已安装模型",
            "dock.noModelsDownloaded": "还没有下载模型。",
            "dock.stopHelp": "停止",
            "dock.loadHelp": "加载到内存",
            "dock.deleteHelp": "从磁盘删除",
            "dock.removeTitle": "移除 %@？",
            "dock.removeButton": "移除 %@",

            "inspector.pulls": "下载量",
            "inspector.tags": "标签",
            "inspector.updated": "更新",
            "inspector.deploy": "部署",
            "inspector.deployHint": "一次点击 = 下载 + 加载",
            "inspector.sizeHint": "下载大小按 Q4 量化估算。",
            "inspector.viewOnOllama": "在 ollama.com 查看",
            "inspector.ram": "~%@ 内存",
            "chip.running": "运行中",
            "chip.installed": "已安装",
            "button.cancel": "取消",
            "button.stop": "停止",
            "button.start": "启动",
            "button.deploy": "部署",
            "button.tooLarge": "过大",
            "button.done": "完成",
            "button.install": "安装",
            "button.restart": "重启",
            "button.send": "发送",
            "button.test": "测试",
            "button.remove": "移除",
            "button.clear": "清空",
            "button.clearHistory": "清空历史",
            "button.quit": "退出",
            "inspector.tooLargeHelp": "预计会超过这台 Mac 的 %d GB 内存",
            "progress.loadingIntoMemory": "正在加载到内存...",
            "progress.ready": "已就绪",
            "progress.failed": "失败：%@",

            "endpoint.title": "连接信息",
            "endpoint.connection": "状态",
            "endpoint.urls": "服务地址",
            "endpoint.configuration": "接入示例",
            "endpoint.readyTitle": "可以连接了",
            "endpoint.waitingTitle": "Ollama 还没启动",
            "endpoint.live": "把应用连接到下面地址，就能使用这台 Mac 上的模型。",
            "endpoint.offline": "先启动 Ollama，再复制连接信息。",
            "endpoint.baseURLs": "基础 URL",
            "endpoint.openAIBase": "通用连接地址",
            "endpoint.primaryHint": "大多数应用、SDK 和 agent 工具用这一项。",
            "endpoint.primaryBadge": "推荐",
            "endpoint.nativeAPI": "Ollama 地址",
            "endpoint.nativeHint": "只有使用 Ollama 原生接口时才需要。",
            "endpoint.model": "模型",
            "endpoint.currentModel": "模型",
            "endpoint.modelHint": "用于下面的示例和测试。",
            "endpoint.noModel": "还没有可用模型",
            "endpoint.dropInConfig": "可直接替换的配置",
            "endpoint.snippetTitle": "复制示例",
            "endpoint.apiKeyHint": "本地使用时，API key 填 ollama 即可。",
            "endpoint.environment": "终端",
            "endpoint.pythonSDK": "Python",
            "endpoint.visionExample": "图片输入",
            "endpoint.toolsExample": "工具调用",
            "endpoint.embeddingExample": "嵌入向量",
            "endpoint.copy": "复制",
            "endpoint.copied": "已复制",
            "test.title": "能力测试",
            "test.deployFirst": "请先启动一个模型。",
            "test.sendPrompt": "发送给 %@。",
            "test.placeholder": "输入一句话试试...",
            "test.placeholderImage": "问问这张图片...",
            "test.placeholderTools": "问问新加坡天气...",
            "test.placeholderEmbedding": "输入要转成向量的文本...",
            "test.response": "模型回复",
            "test.toolResult": "工具调用",
            "test.embeddingResult": "嵌入结果",
            "test.defaultPrompt": "用一句话打个招呼。",
            "test.defaultImagePrompt": "用一段话描述这张图片。",
            "test.defaultToolsPrompt": "新加坡现在天气怎么样？请使用工具。",
            "test.defaultEmbeddingPrompt": "本地模型可以让私有 AI 工作流成为可能。",
            "test.modeText": "文本",
            "test.modeImage": "图片",
            "test.modeTools": "工具",
            "test.modeEmbedding": "嵌入",
            "test.capText": "文本对话",
            "test.capVision": "图片输入",
            "test.capTools": "工具调用",
            "test.capEmbedding": "嵌入向量",
            "test.chooseImage": "选择图片",
            "test.changeImage": "更换",
            "test.pasteImage": "粘贴",
            "test.pastedImage": "粘贴的图片",
            "test.noImageOnClipboard": "剪贴板里没有图片。",
            "test.imageReady": "可发送给视觉模型。",
            "test.imagePickHint": "选择或粘贴一张图片。",
            "test.embeddingHint": "嵌入请求可能需要 Ollama 以 embedding 支持模式启动。",

            "settings.title": "设置",
            "settings.basic": "常用",
            "settings.language": "语言",
            "settings.languageSubtitle": "切换界面显示语言。",
            "settings.ollama": "本地模型服务",
            "settings.runtime": "运行时",
            "settings.runtimeSubtitle": "Ollama 在本机运行模型。",
            "settings.binary": "可执行文件",
            "settings.modelList": "模型列表",
            "settings.modelListSubtitle": "刷新或排序在线模型列表。",
            "settings.modelLibrary": "可浏览模型",
            "settings.modelCount": "%d 个模型",
            "settings.notSynced": "尚未同步",
            "settings.keepAlive": "多久后释放模型",
            "settings.keepAliveSubtitle": "模型空闲后，会按这个时间从内存释放。",
            "settings.fiveMin": "5 分钟",
            "settings.thirtyMin": "30 分钟",
            "settings.twoHours": "2 小时",
            "settings.forever": "一直保留",
            "settings.menuBarStartup": "菜单栏和启动项",
            "settings.menuBarSubtitle": "菜单栏图标可在不打开主窗口时启动/停止模型。",
            "settings.launchAtLogin": "开机自动启动",
            "settings.launchAtLoginSubtitle": "重启后也能从菜单栏快速打开。",
            "settings.history": "历史记录",
            "settings.historySubtitle": "你部署、启动、停止或移除过的模型。",
            "settings.historyCount": "%d 条记录",
            "settings.nothingYet": "还没有记录。",
            "settings.storage": "存储",
            "settings.downloadedModels": "已下载模型",
            "settings.downloadedModelsSubtitle": "删除后以后还可以重新下载。",
            "settings.cleanUp": "清理",
            "settings.cleanUpSubtitle": "保持主机干净：停止就是停止，删除就是删除。",
            "settings.modelsOnDisk": "磁盘上的模型",
            "settings.removeAllModels": "删除已下载模型",
            "settings.removeAllTitle": "删除 %d 个已下载模型？",
            "settings.removeAllMessage": "只会删除下载的模型，Ollama 会继续保留。",
            "settings.resetHost": "卸载 Ollama 和全部数据",
            "settings.resetTitle": "重置这台主机？",
            "settings.resetButton": "卸载 Ollama 并删除模型数据",
            "settings.resetMessage": "会停止所有模型、删除下载内容、卸载 Ollama，并清空 ~/.ollama。",
            "settings.cleaning": "清理中...",
            "settings.advanced": "高级设置",
            "settings.footer": "ModelChanges - 实时浏览开放模型，并一键部署到本机。检测到这台 Mac 有 %d GB 内存。",
            "runtime.ready": "服务正在运行",
            "runtime.running": "Ollama %@ 已就绪。",
            "runtime.installedNotRunning": "服务未启动",
            "runtime.startHint": "启动后才能使用本地模型。",
            "runtime.notInstalled": "还没有安装 Ollama",
            "runtime.installHint": "安装后即可在这台 Mac 上运行模型。",

            "menu.noModelsLoaded": "没有加载模型",
            "menu.startInstalled": "启动模型",
            "menu.launchAtLogin": "登录时启动",
            "menu.openApp": "打开",
            "menu.on": "在线",
            "menu.off": "离线",
            "menu.loadedCount": "%d 个已加载",
            "menu.serverNotRunning": "服务未运行",
            "menu.ollamaNotInstalled": "未安装 Ollama",

            "log.synced": "已从 ollama.com 同步 %d 个模型",
            "log.deploying": "正在部署 %@...",
            "log.cancelled": "已取消 %@",
            "log.ready": "%@ 已就绪",
            "log.stopping": "正在停止 %@...",
            "log.stopped": "已停止 %@",
            "log.removing": "正在移除 %@...",
            "log.removed": "已移除 %@",
            "log.removingAll": "正在移除全部模型...",
            "log.removedAll": "已移除 %d 个模型",
            "log.resettingHost": "正在重置主机...",
            "log.hostCleaned": "主机已清理 - Ollama 已卸载",
            "log.startingServer": "正在启动 Ollama 服务...",
            "log.serverUp": "Ollama 服务已在线",
            "log.installingOllama": "正在安装 Ollama（可能需要一点时间）...",
            "log.ollamaInstalled": "Ollama 已安装",
            "log.installFailed": "安装失败 - 请查看错误提示",
            "error.ollamaInstallFailed": "Ollama 安装失败：%@",
            "error.syncFailed": "同步失败：%@",
            "error.homebrewNotFound": "无法自动安装 Ollama。",
            "error.brewInstallFailed": "Ollama 安装失败：%@",
            "error.failedTag": "%@：%@",
            "log.failedTag": "%@ 失败：%@"
        ]
    ]
}
